### ISSUE TITLE
styled-components and recompose shouldn't be a peer dependency

### ISSUE THREAD

**Issue by ghost** [Astrocoders/react-native-tooltip-view#3]
Your package.json has a peer dependency on `styled-components`, which I don't use. You should set `styled-components` and `recompose` to be dependencies of your own package, as they can't be guaranteed to be available.

**Comment by fakenickels** [comment]
Indeed for this case makes sense, could you PR us on this?
Thanks

**Comment by ghost** [comment]
Done

#4

**Comment by fakenickels** [comment]
actually  @RobertSheaO, I saw here that duplicated instances of styled-components will cause a problem in the code in the browser https://github.com/styled-components/styled-components/issues/1032. As for RN I haven't tested that. But AFAIK seems that including it as a peer dependency is the best approach.
I think that will better to update the README installation steps to also warn to install styled-components and recompose.
